name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flask-demo-app:${{ github.sha }}

    - name: Update Kubernetes manifests
      run: |
        sed -i 's#image: .*#image: ${{ secrets.DOCKER_HUB_USERNAME }}/flask-demo-app:${{ github.sha }}#g' deploy/deployment.yaml
        git config --local user.email "${{ secrets.EMAIL_ADDRESS }}"
        git config --local user.name "${{ github.actor }}"
        git add deploy/deployment.yaml
        git commit -m "Update image version to ${{ github.sha }}"
        git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git main

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deploy/deployment.yaml
        kubectl apply -f deploy/service.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
